Update smbase/array.h
Fixes compilation with gcc 4.7

array.h: In instantiation of ‘void ArrayStack<T>::push(const T&) [with T = BPBox*]’:
array.h:372:32:   required from ‘void ObjArrayStack<T>::push(T*) [with T = BPBox]’
boxprint.cc:371:39:   required from here
array.h:261:7: error: ‘setIndexDoubler’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
array.h:261:7: note: declarations in dependent base ‘GrowArray<BPBox*>’ are not found by unqualified lookup
array.h:261:7: note: use ‘this->setIndexDoubler’ instead